.Dd December 27, 2023
.Dt mouseTrail 1
.Os
.Sh NAME
.Nm mouseTrail
.Nd fun little mouse trail
.Sh SYNOPSIS
.Nm
.Sh DESCRIPTION
.Nm
is a fun little program which uses the X window system
to create a mouse trail, potentially with a rainbow effect.
.Sh EXIT STATUS
.TS
allbox;
lb lb
l l.
Return Value	Meaning
2	Cannot find the specified initCursor file
11	Cannot connect to the X server
.TE
.Sh CUSTOMIZATION
.Nm
can be customized be editing the variables under
.Ar /* config */
near the top of the source, and recompiling.
.Sh CURSORS
.Nm
cursors are stored as xpm files and are selected
either by the name given by Xorg, or the location of
the hotspot formatted as
.Ar xhot
-
.Ar yhot
\&.xpm
.Pp
The xpms do not include transparency by default, and
so one color (set by the emptyColor, in config) is
replaced with transparency.
.Pp
If the current cursor has no name and has its hotspot at
(0, 0), then
.Nm
will stop and wait until another mouse cursor is used.
.Sh RAINBOW MODE
Rainbow mode works by replacing a single color in each copy
with rainbow (set in config).
