.Dd June 26, 2024
.Dt mouseTrail 1
.Os
.Sh NAME
.Nm mouseTrail
.Nd fun little mouse trail
.Sh SYNOPSIS
.Nm
.Sh DESCRIPTION
.Nm
is a fun little program which uses the X window system
to create a mouse trail, optionally with a rainbow effect.
.Sh EXIT STATUS
.TS
allbox;
lb lb
l l.
Return Value	Meaning
11	Cannot connect to the X server
.TE
.Sh CUSTOMIZATION
.Nm
can be customized be editing the variables under
.Ar /* config */
near the top of the source, and recompiling.
.Pp
The behavior of rainbow mode is contained between lines
123 and 133.
.Sh RAINBOW MODE
Rainbow mode works by replacing either the all, only lighter,
or only darker (set in config) pixels with a random color in
each copy with rainbow.
